#+TITLE: Tennis Ball Collector

Ceci est un template de dépôt Git pour le cours d'ingénierie système et modélisation robotique à l'ENSTA Bretagne en 2021.

* Launch the simulation

** Requirements
In order to run the simulation, you'll need to install the following dependencies:
- [[https://pypi.org/project/imutils/][imutils]]

** Run the simulation

A compléter avec la/les commande(s) à lancer.
#+begin_src bash :tangle no :export code :results silent
# TODO
#+end_src

* Modules
** Waypoint generation node
*** Description:
Generation of a waypoint for the robot at each instant, based on the known position of the balls.

*** Communication:
- Subscribers ::
  - =/ball_list= : Float64MultiArray

- Publishers ::
  - =/waypoint= : Pose.

** Example node
*** Description:
A very cool module.

*** Communication:
- Subscribers ::
  - =/input_node_name= : type_of_the_message

- Publishers ::
  - =/output_node_name= : type_of_the_message

** Control node
*** Description:

*** Communication:
- Subscribers ::

- Publishers ::

** Top camera node
*** Description:
This node, camera_top , publish the positions and identifications for all balls with information of the camera.

*** Communication:
- Subscribers ::
  - =/zenith_camera/image_raw= : Image

- Publishers ::
  - =/ball_list= : Float64MultiArray

** World model
*** Description:

*** Communication:

* Group

** Members
Yves Jordan NJAMEN, Stéphane WEMBE, Bernardo HUMMES FLORES, Yohann GOURRET, Katell LAGATTU


** Project Management
The project in Taiga can be found [[https://tree.taiga.io/project/birromer-1-tennis-ball-collector/timeline][here]].

* Repository structure
This repository must be cloned inside the =src= directory of a ROS2 workspace.

** `tennis_court` package
The folder =tennis_court= is a ROS package containing the world in which the ball cleaning ball.

Le dossier `tennis_court` est un package ROS contenant le monde dans lequel le robot ramasseur de balle devra évoluer ainsi qu'un script permettant de faire apparaître des balles dans la simulation.
Ce package ne doit pas être modifié.
Consulter le [README](tennis_court/README.md) du package pour plus d'informations.


** Documents

Le dossier `docs` contient tous les documents utiles au projet:
- Des [instructions pour utiliser Git](docs/GitWorkflow.md)
- Un [Mémo pour ROS 2 et Gazebo](docs/Memo_ROS2.pdf)
- Les [slides de la présentation Git](docs/GitPresentation.pdf)


** Rapports

Le dossier `reports` doit être rempli avec les rapports d'[objectifs](../reports/GoalsTemplate.md) et de [rétrospectives](../reports/DebriefTemplate.md) en suivant les deux templates mis à disposition. Ces deux rapports doivent être rédigés respectivement au début et à la fin de chaque sprint.
