#+TITLE: Debriefing for 21/01/2022

PO: Capitaine Katell Lagattu

* Review

Percentage of accomplished tasks: 70 %

** What worked
- create a workspace with ROS2 and have the same environment on each PC
- define a communication pattern between topics
- display robot in Gazebo
- access to the camera data of the scene


** What did not work
- the gripper has not been yet designed
- the ball localisation isn't finished yet

** PO experience
We spent a lot of time strategizing together, and sometimes we had a little trouble understanding each other.
I was surprised at how much time it took to set up the SCRUM method, and I didn't have time to code much.
However, it was a very good experience because the team gets along very well.


** Advice for the next PO
I think we need to use the board more to express your ideas because it is sometimes difficult to get into the head of others.
I think we should improve the system of assigning tasks, and make it clear to everyone.


* New decisions
- set up a common naming system
- better distribution of tasks
