<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="carlos">

   <xacro:property name="body_x" value="0.5" />
   <xacro:property name="body_y" value="0.3" />
   <xacro:property name="body_z" value="0.2" />
   <xacro:property name="body_m" value="1.0" />

   <xacro:property name="wheel_len" value="0.04" />
   <xacro:property name="wheel_rad" value="0.1" />
   <xacro:property name="wheel_m" value="0.1" />

   <xacro:property name="wheel_front_rad" value="0.07" />
   <xacro:property name="wheel_front_m" value="0.2" />

   <xacro:property name="cam_rad" value="0.04" />
   <xacro:property name="cam_m" value="0.01" />

<!--    <xacro:property name="lidar_len" value="0.08" />
   <xacro:property name="lidar_rad" value="0.06" />
   <xacro:property name="lidar_m" value="0.05" /> -->

    <!-- Define intertial property macros  -->
   <xacro:macro name="box_inertia" params="m w h d">
     <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0"
              iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) *
(w*w + h*h)}" />
   </xacro:macro>

   <xacro:macro name="cylinder_inertia" params="m r h">
     <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0"
              iyy="${(m/12) * (3*r*r + h*h)}" iyz="0" izz="${(m/2) *
(r*r)}" />
   </xacro:macro>

   <xacro:macro name="sphere_inertia" params="m r">
     <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0"
              iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m *
(r*r)}" />
   </xacro:macro>

  <xacro:macro name="sphere_link" params="name r color mass:=0.1 inertia_ratio:=1.0 *origin">
    <link name="${name}">
        <collision>
            <xacro:insert_block name="origin"/>
            <geometry>
                <sphere radius="${r}"/>
            </geometry>
        </collision>
        <visual>
            <xacro:insert_block name="origin"/>
            <geometry>
                <sphere radius="${r}"/>
            </geometry>
            <material name="${color}"/>
        </visual>
        <inertial>
            <mass value="${mass}"/>
            <xacro:insert_block name="origin"/>
            <inertia ixx="${inertia_ratio*(2/3)*mass*r*r}" ixy="0.0" ixz="0.0"
                     iyy="${inertia_ratio*(2/3)*mass*r*r}" iyz="0.0"
                     izz="${inertia_ratio*(2/3)*mass*r*r}"/>
        </inertial>
    </link>
    <joint name="${name}_joint" type="fixed">
       <parent link="base_link"/>
       <child link="${name}"/>
       <xacro:insert_block name="origin"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="gripper_link" params="name l thickness h color mass:=0.1 inertia_ratio:=1.0 *origin">
    <link name="${name}">
        <collision>
            <xacro:insert_block name="origin"/>
            <geometry>
              <box size="${l} ${thickness} ${h}"/>
            </geometry>
        </collision>
        <visual>
            <xacro:insert_block name="origin"/>
            <geometry>
              <box size="${l} ${thickness} ${h}"/>
            </geometry>
            <material name="${color}"/>
        </visual>
        <inertial>
            <mass value="${mass}"/>
            <xacro:insert_block name="origin"/>
            <inertia ixx="${mass/12} * (${l}*${l})" ixy="0.0" ixz="0.0" iyy="${mass/12} * (${thickness}*${thickness})" iyz="0.0" izz="${mass/12}*(${thickness}*${thickness} + ${h}*${h})" />
        </inertial>
    </link>
    <joint name="${name}_joint" type="fixed">
       <parent link="base_link"/>
       <child link="${name}"/>
       <xacro:insert_block name="origin"/>
    </joint>
    <gazebo reference="wheel_front">
     <material>Gazebo/DarkGray</material>
     <mu1>0.2</mu1>
     <mu2>0.2</mu2>
    </gazebo>
  </xacro:macro>

  <material name="blue">
   <color rgba="0 0 0.8 1"/>
  </material>

  <material name="red">
   <color rgba="0.8 0 0 1"/>
  </material>

  <material name="grey">
   <color rgba="0.36 0.36 0.36 1"/>
  </material>

  <material name="lightgrey">
   <color rgba="0.76 0.76 0.76 1"/>
  </material>

  <material name="white">
   <color rgba="1 1 1 1"/>
  </material>

  <material name="violet">
   <color rgba="${127/255} ${0/255} 1 1"/>
  </material>

  <material name="green">
   <color rgba="0 1 0 1"/>
  </material>

  <link name="base_link">
   <visual>
     <geometry>
       <box size="${body_x} ${body_y} ${body_z}"/>
     </geometry>
     <material name="white"/>
   </visual>

   <collision>
     <geometry>
       <box size="${body_x} ${body_y} ${body_z}"/>
     </geometry>
   </collision>

   <inertial>
     <origin rpy="0 0 0" xyz="0 0 0.0"/>
     <mass value="${body_m}"/>
     <xacro:box_inertia m="${body_m}" w="${body_y}" h="${body_z}"
  d="${body_x}"/>
   </inertial>
  </link>

  <gazebo reference="base_link">
   <material>Gazebo/White</material>
  </gazebo>

  <link name="wheel_right">
   <visual>
     <geometry>
       <cylinder length="${wheel_len}" radius="${wheel_rad}"/>
     </geometry>
     <material name="lightgrey"/>
   </visual>

   <collision>
     <geometry>
       <cylinder length="${wheel_len}" radius="${wheel_rad}"/>
     </geometry>
   </collision>

   <inertial>
     <mass value="${wheel_m}"/>
     <xacro:cylinder_inertia m="${wheel_m}" r="${wheel_rad}"
  h="${wheel_len}"/>
   </inertial>
  </link>

  <gazebo reference="wheel_right">
   <mu1>1.2</mu1>
   <mu2>1.2</mu2>
   <kp>500000.0</kp>
   <kd>10.0</kd>
   <minDepth>0.001</minDepth>
   <maxVel>0.1</maxVel>
   <material>Gazebo/FlatBlack</material>
  </gazebo>

  <joint name="wheel_right_joint" type="continuous">
   <parent link="base_link"/>
   <child link="wheel_right"/>
   <axis xyz="0 0 1"/>
   <origin rpy="${-pi/2} 0 0" xyz="${body_x*0.2} ${-body_y*0.65}
  ${-body_y*0.25}"/>
  </joint>

  <link name="wheel_left">
   <visual>
     <geometry>
       <cylinder length="${wheel_len}" radius="${wheel_rad}"/>
     </geometry>
     <material name="lightgrey"/>
   </visual>

   <collision>
     <geometry>
       <cylinder length="${wheel_len}" radius="${wheel_rad}"/>
     </geometry>
   </collision>

   <inertial>
     <mass value="${wheel_m}"/>
     <xacro:cylinder_inertia m="${wheel_m}" r="${wheel_rad}"
  h="${wheel_len}"/>
   </inertial>
  </link>

  <gazebo reference="wheel_left">
   <mu1>1.2</mu1>
   <mu2>1.2</mu2>
   <kp>500000.0</kp>
   <kd>10.0</kd>
   <minDepth>0.001</minDepth>
   <maxVel>0.1</maxVel>
   <material>Gazebo/FlatBlack</material>
  </gazebo>

  <joint name="wheel_left_joint" type="continuous">
   <parent link="base_link"/>
   <child link="wheel_left"/>
   <axis xyz="0 0 1"/>
   <origin rpy="${-pi/2} 0 0" xyz="${body_x*0.2} ${body_y*0.65}
  ${-body_y*0.25}"/>
  </joint>

  <link name="wheel_front">
   <visual>
     <geometry>
       <sphere radius="${wheel_front_rad}"/>
     </geometry>
     <material name="grey"/>
   </visual>
   <collision>
     <geometry>
       <sphere radius="${wheel_front_rad}"/>
     </geometry>
   </collision>
  </link>
  <joint name="wheel_front_joint" type="fixed">
   <parent link="base_link"/>
   <child link="wheel_front"/>
   <origin rpy="0 0 0" xyz="${-body_x*0.325} 0.0 ${-body_z*0.5}"/>
  </joint>

  <gazebo reference="wheel_front">
   <material>Gazebo/DarkGray</material>
   <mu1>0.2</mu1>
   <mu2>0.2</mu2>
  </gazebo>

  <!-- ______________ wheel motion plugin _______________  -->
  <gazebo>
   <plugin filename="libgazebo_ros_diff_drive.so" name="diff_drive">
     <!-- wheels -->
     <left_joint>wheel_left_joint</left_joint>
     <right_joint>wheel_right_joint</right_joint>
     <!-- kinematics -->
     <wheel_separation>${wheel_len + body_y}</wheel_separation>
     <wheel_diameter>${2*wheel_rad}</wheel_diameter>
     <!-- limits -->
     <max_wheel_torque>50</max_wheel_torque>
    <max_wheel_acceleration>5.0</max_wheel_acceleration>
     <!-- output -->
     <publish_odom>true</publish_odom>
     <publish_odom_tf>true</publish_odom_tf>
     <publish_wheel_tf>true</publish_wheel_tf>
     <robot_base_frame>base_link</robot_base_frame>
   </plugin>
  </gazebo>

   <!-- ______________ sphere orientation _______________  -->
  <xacro:sphere_link name="green_head_sphere" color="green" r="0.05" mass="0.02" inertia_ratio="0.01">
    <origin xyz="${-body_x*0.15} 0.0 ${body_z*0.25}" rpy="0 0 0"/>
  </xacro:sphere_link>
  <gazebo reference="green_head_sphere">
    <material>Gazebo/Green</material>
  </gazebo>
  <xacro:sphere_link name="violet_head_sphere" color="violet" r="0.05" mass="0.02" inertia_ratio="0.01">
    <origin xyz="${body_x*0.15} 0.0 ${body_z*0.25}" rpy="0 0 0"/>
  </xacro:sphere_link>
  <gazebo reference="violet_head_sphere">
    <material>Gazebo/Purple</material>
  </gazebo>


  <!-- ______________ adding grepper _______________  -->
<!--   <xacro:gripper_link name="right_gripper_1" l="${body_x*0.65}" thickness="${body_y*0.05}" h="${body_z*0.5}"  color="grey" mass="0.1" inertia_ratio="0.01">
    <origin xyz="${body_x*0.3} ${-body_y*0.1} ${-body_z*0.2}" rpy="0 0 ${-pi/8}"/>
  </xacro:gripper_link>
  <xacro:gripper_link name="right_gripper_2" l="${body_x*0.15}" thickness="${body_y*0.05}" h="${body_z*0.5}"  color="grey" mass="0.1" inertia_ratio="0.01">
    <origin xyz="${body_x*0.4*cos(pi/8)} ${-body_x*0.75*sin(pi/8)} ${-body_z*0.2}" rpy="0 0 ${pi/8}"/>
  </xacro:gripper_link>
  <xacro:gripper_link name="left_gripper_1" l="${body_x*0.65}" thickness="${body_y*0.05}" h="${body_z*0.5}"  color="grey" mass="0.1" inertia_ratio="0.01">
    <origin xyz="${body_x*0.3} ${body_y*0.1} ${-body_z*0.2}" rpy="0 0 ${pi/8}"/>
  </xacro:gripper_link>
  <xacro:gripper_link name="left_gripper_2" l="${body_x*0.15}" thickness="${body_y*0.05}" h="${body_z*0.5}"  color="grey" mass="0.1" inertia_ratio="0.01">
    <origin xyz="${body_x*0.4*cos(-pi/8)} ${-body_x*0.75*sin(-pi/8)} ${-body_z*0.2}" rpy="0 0 ${-pi/8}"/>
  </xacro:gripper_link> -->

  <xacro:gripper_link name="right_gripper_1" l="${body_x*0.6}" thickness="${body_y*0.05}" h="${body_z*0.6}"  color="grey" mass="0.1" inertia_ratio="0.01">
    <origin xyz="${body_x*0.36} ${-body_y*0.05} ${-body_z*0.2}" rpy="0 0 ${-pi/8}"/>
  </xacro:gripper_link>
  <xacro:gripper_link name="right_gripper_2" l="${body_x*0.15}" thickness="${body_y*0.05}" h="${body_z*0.6}"  color="grey" mass="0.02" inertia_ratio="0.01">
    <origin xyz="${body_x*0.46*cos(pi/8)} ${-body_x*0.71*sin(pi/8)} ${-body_z*0.2}" rpy="0 0 ${pi/8}"/>
  </xacro:gripper_link>
  <xacro:gripper_link name="left_gripper_1" l="${body_x*0.6}" thickness="${body_y*0.05}" h="${body_z*0.6}"  color="grey" mass="0.02" inertia_ratio="0.01">
    <origin xyz="${body_x*0.36} ${body_y*0.05} ${-body_z*0.2}" rpy="0 0 ${pi/8}"/>
  </xacro:gripper_link>
  <xacro:gripper_link name="left_gripper_2" l="${body_x*0.15}" thickness="${body_y*0.05}" h="${body_z*0.6}"  color="grey" mass="0.1" inertia_ratio="0.01">
    <origin xyz="${body_x*0.46*cos(-pi/8)} ${-body_x*0.71*sin(-pi/8)} ${-body_z*0.2}" rpy="0 0 ${-pi/8}"/>
  </xacro:gripper_link>

  <!-- ______________ adding imu _______________  -->
    <link name="imu_link">
     <visual>
       <geometry>
         <sphere radius="${0.02}"/>
       </geometry>
       <material name="grey"/>
     </visual>
   </link>

  <joint name="imu_joint" type="fixed">
   <parent link="base_link"/>
   <child link="imu_link"/>
   <origin rpy="0 0 0" xyz="${0.0} 0.0 ${0.0}"/>
  </joint>

  <gazebo reference="imu_link">
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <ros>
            <remapping>~/out:=imu</remapping>
          </ros>
        <topicName>imu</topicName>
        <bodyName>imu_link</bodyName>
        <updateRateHZ>10.0</updateRateHZ>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_link</frameName>
        <gaussianNoise>0.01</gaussianNoise>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo>

</robot>